// src/features/userSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Define initial state for the user (with example fields)
const initialState = {
  name: '',
  email: '',
  isAuthenticated: false,
};

const userSlice = createSlice({
  name: 'user',  // Name for this slice
  initialState,   // Initial state for this slice
  reducers: {
    login: (state, action) => {  // Login action
      state.isAuthenticated = true;
      state.name = action.payload.name;
      state.email = action.payload.email;
    },
    logout: (state) => {  // Logout action
      state.isAuthenticated = false;
      state.name = '';
      state.email = '';
    }
  },
});

// Export actions (generated by createSlice)
export const { login, logout} = userSlice.actions;

// Export the reducer
export default userSlice.reducer;
